language: perl
before_install:
    - cpanm --notest JSON YAML Text::CSV Text::CSV_XS Math::Matrix HTML::TableExtract Spreadsheet::ParseExcel
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
